### ISSUE TITLE
video.js controls

### ISSUE THREAD

**Issue by nppsbh** [matthojo/videojs-Background#8]
Hi.
Is it possible to use video.js control bar when using videojs-Background? Because they are not visible. Probably due to screen resolution?
Thanks

**Comment by matthojo** [comment]
Currently this is not possible, sorry. videojs-background is intentionally 'control-less' so the background elements is all video.

**Comment by Loac-fr** [comment]
Just in case, as I needed the same thing for testing purpose : 
Assuming you have a relative positionned body or parent, add this css : 

``` css
.vjs-default-skin.vjs-has-started .vjs-control-bar{
    width: 50%;
    left: 50%;
    bottom: 1vh;
    transform: translateX(-50%);
    z-index: 1000;
}
```
